name: Merge Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - "*"
      
jobs:
  merge-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # or whichever version of Python your plugin requires

      - name: Install plugin dependencies
        run: pip install -r requirements.txt

      - name: Run plugin checks
        run: python Manual-Approval-Check.py
