name: Assign PR to User

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]

jobs:
  assign-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assign PR to User
        env:
          USER_TO_ASSIGN: armin-mahina
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "pull_request_review" ]]; then
            if [[ "${{ github.event.review.state }}" == "approved" ]]; then
              PR_NUMBER="${{ github.event.pull_request.number }}"
              curl -X POST -H "Authorization: token $GIT_TOKEN" -d "{\"assignees\":[\"${USER_TO_ASSIGN}\"]}" "https://api.github.com/repos/mk-mahina/PR-Merge-DryRun/issues/${PR_NUMBER}/assignees"
            fi
          elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            if [[ "${{ github.event.pull_request.state }}" == "open" ]]; then
              PR_NUMBER="${{ github.event.pull_request.number }}"
              PR_APPROVED=$(curl -s -H "Authorization: token $GIT_TOKEN" "https://api.github.com/repos/mk-mahina/PR-Merge-DryRun/pulls/${PR_NUMBER}/reviews?per_page=100" | grep -c "\"state\":\"APPROVED\"")
              if [[ "$PR_APPROVED" -eq "1" ]]; then
                curl -X POST -H "Authorization: token $GIT_TOKEN" -d "{\"assignees\":[\"${USER_TO_ASSIGN}\"]}" "https://api.github.com/repos/mk-mahina/PR-Merge-DryRun/issues/${PR_NUMBER}/assignees"
              fi
            fi
          fi
