name: Merge Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - "*"
      
jobs:
  merge-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install plugin dependencies
        run: pip install -r requirements.txt

      - name: Run plugin checks
        run: python pr-merge.py
