name: Merge Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  merge-checks:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Install plugin dependencies
        run: pip install -r requirements.txt

      - name: Check if PR is approved
        id: pr-check
        run: |
          echo "GIT_TOKEN: ${{ secrets.GIT_TOKEN }}"
          pr_url="${{ github.event.pull_request.url }}"
          approval_url="${pr_url}/reviews?state=APPROVED"
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" "$approval_url")
          approved_count=$(echo "$response" | jq '. | length')
          if [[ "$approved_count" -gt 0 ]]; then
            echo ::set-output name=approved::true
          else
            echo ::set-output name=approved::false
          fi
        shell: bash

      - name: Assign PR to armin-mahina if approved
        if: ${{ steps.pr-check.outputs.approved == 'true' }}
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          echo "GIT_TOKEN: ${{ secrets.GIT_TOKEN }}"          
          python pr-merge.py ${{ secrets.GIT_TOKEN }}
