name: Merge Check and Assign

on:
  pull_request_review:
    types: [submitted, edited]
  pull_request:
    types: [labeled]

jobs:
  merge_check_and_assign:
    runs-on: ubuntu-latest
    steps:
    - name: Check if all required reviews are approved
      uses: google/github-actions/checks/mergeable@main
      id: merge-check
      with:
        required_approvals: 1
    - name: Assign PR to user if approved
      if: ${{ steps.merge-check.outputs.mergeable == 'true' }}
      uses: peter-evans/create-issue-comment@v1.6.0
      with:
        body: 'This PR has been approved and is ready to be merged!'
        issue-number: ${{ github.event.pull_request.number }}
        repo-token: ${{ secrets.SECRET_TOKEN }}
      - name: Assign PR to user
        if: ${{ steps.merge-check.outputs.mergeable == 'true' }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.SECRET_TOKEN }}
          script: |
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ['armin-mahina']
            })
