name: Manual Merge Approval Check

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [synchronize]

jobs:
  merge-approval-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run merge approval check
        run: python pr-merge-plugin.py
        if: ${{ steps.pr-check.outputs.num_approvals == 1 }}


