name: Manual Merge Approval Check

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [synchronize]

jobs:
  merge-approval-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check pull request review status
        id: pr-check
        uses: softprops/action-timer@v1
        with:
          timeout-minutes: 10
          command: |
            reviews=$(curl -s -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews)
            num_approvals=$(echo $reviews | jq '.[] | select(.state=="APPROVED") | .user.login' | sort -u | wc -l)
            echo "::set-output name=num_approvals::$num_approvals"

      - name: Run merge approval check
        run: python pr-merge-plugin.py
        if: ${{ steps.pr-check.outputs.num_approvals == 1 }}

      - name: Set status check
        uses: github/set-status-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: ${{ job.status }}
          description: "Merge approval check"
          context: "merge-approval-check"
        if: ${{ steps.pr-check.outputs.num_approvals == 1 }}