name: Jira Transition on PR Merge

on:
  pull_request:
    types: [closed]
    # Trigger only when a PR is merged
    if: github.event.pull_request.merged == true

jobs:
  jira-transition:
    runs-on: ubuntu-latest
    steps:
      - name: Get Jira issue key from branch name
        id: get-jira-issue-key
        run: |
          echo "github.event.pull_request.head.ref=${{ github.event.pull_request.head.ref }}"
          echo "jira-issue-key=$(echo ${{ github.event.pull_request.head.ref }} | sed -nE 's#^([A-Z]+-[0-9]+).*#\1#p')" >> $GITHUB_ENV

      - name: Show Jira issue key
        run: echo ${{ env.jira-issue-key }}

      - name: Transition Jira issue from pending PR QA --> pending Production 
        env:
          JIRA_AUTH_TOKEN: ${{ secrets.JIRA_AUTH_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}          
          JIRA_TRANSITION_ID: "91"
        run: |    
          echo "jira-issue-key=${{ env.jira-issue-key }}"
          echo "JIRA_TRANSITION_ID=$JIRA_TRANSITION_ID"
          curl -D- -u $JIRA_USER:$JIRA_AUTH_TOKEN \
            -X POST \
            -H "Content-Type: application/json" \
            --data "{\"transition\": {\"id\": \"$JIRA_TRANSITION_ID\"}}" \
            $JIRA_BASE_URL/rest/api/2/issue/${{ env.jira-issue-key }}/transitions"
