name: PR Assignment

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]

jobs:
  merge-check:
    runs-on: ubuntu-latest    
    if: >
      github.event.review.state == 'approved' &&
      github.event.review.user.login != 'armin-mahina'
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2