name: PR Troubleshooting

on:
  pull_request_review:
    types: [submitted]
    properties:
      review: approved

jobs:
  merge-check:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.state == 'open' }}
    steps:
      - name: Print review state and reviewer
        run: |
          echo "Review state: ${{ github.event.review.state }}"
          echo "Reviewer: ${{ github.event.review.user.login }}"
      - name: Checkout code
        uses: actions/checkout@v2