name: PR Assignment

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]

jobs:
  merge-check:
 
    steps:
      - name: Debug User Login
        run: |
          echo "User Login: ${{ github.event.review.user.login }}"
      - name: Debug Review State
        run: |
          echo "Review State: ${{ github.event.review.state }}"

  