name: PR Troubleshooting

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]

jobs:
  merge-check:
    runs-on: ubuntu-latest
    steps:
      - name: Print review state and reviewer
        run: |
          echo "Review state: ${{ github.event.review.state }}"
          echo "Reviewer: ${{ github.event.review.user.login }}"
      - name: Checkout code
        uses: actions/checkout@v2
