name: PR Troubleshooting

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print payload
        run: |
          echo ${{ toJson(github.event) }}
