name: PR Assignment

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      - name: Verify PR Approval
        run: |
          if [ "$(curl -s -H "Authorization: Bearer ${{ secrets.SECRET_TOKEN }}" \
                  "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" \
                  | jq '.[] | select(.user.login == "armin-mahina" and .state == "APPROVED")')" = "" ]; then
            echo "PR not approved by armin-mahina"
            curl -X POST \
              -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{"body": "Waiting for the approval from @armin-mahina before merging."}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
            exit 1
          else
            echo "PR approved by armin-mahina"
          fi        
