name: PR Assignment

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get pull request review status
      run: |
        latest_review_state=$(echo "${{ github.event.pull_request.reviews[-1].state }}")
        review_decision=$(echo "${{ github.event.pull_request.review_decision }}")
        if [ "$latest_review_state" == "APPROVED" ] || [ "$review_decision" == "approved" ]; then
          echo "Pull request has been approved"
        else
          echo "Pull request has not been approved"
        fi
